# **100 DAYS OF DATA SCIENCE**

*PHASE 2: 🚀 NUMPY FUNDAMENTALS*

---

### 📊 **NumPy Learning Philosophy**
```
NumPy Mastery = Understanding + Practice + Real-world Application
```

### **Why Master NumPy?**
1. **Foundation** for all data science libraries (Pandas, Scikit-learn, TensorFlow)
2. **Performance** - 10-100x faster than pure Python
3. **Memory efficient** - stores data contiguously
4. **Vectorized operations** - no explicit loops needed

**IMPORT REQUIRED LIBRARIES**

In [1]:
print("="*70)
print("🎯 IMPORT REQUIRED LIBRARIES")
print("="*70)

🎯 IMPORT REQUIRED LIBRARIES


In [2]:
# Import required libraries
import numpy as np
import time
import sys
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(42)

print("✅ Libraries imported successfully!")

✅ Libraries imported successfully!


In [3]:
print("=" * 70)
print("Why NumPy? - Speed & Efficiency")
print("=" * 70)

Why NumPy? - Speed & Efficiency


In [4]:
# Speed comparison: Python list vs NumPy array
size = 1000000

In [5]:
# Test 1: Creating large arrays
print(f"\nCreating {size:,} numbers:")


Creating 1,000,000 numbers:


In [6]:
# Python list
start = time.time()
python_list = list(range(size))
python_time = time.time() - start
print(f"Python list: {python_time:.4f} seconds")

Python list: 0.0378 seconds


In [7]:
# NumPy array
start = time.time()
numpy_array = np.arange(size)
numpy_time = time.time() - start
print(f"NumPy array: {numpy_time:.4f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x faster!\n")

NumPy array: 0.0048 seconds
NumPy is 7.8x faster!



In [8]:
# Test 2: Mathematical operations
print(f"Multiplying {size:,} numbers by 2:")

Multiplying 1,000,000 numbers by 2:


In [9]:
# Python list
start = time.time()
result_list = [x * 2 for x in python_list]
python_time = time.time() - start
print(f"Python list: {python_time:.4f} seconds")

Python list: 0.1454 seconds


In [10]:
# NumPy array
start = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start
print(f"NumPy array: {numpy_time:.4f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x FASTER! 🚀\n")

NumPy array: 0.0058 seconds
NumPy is 25.1x FASTER! 🚀



In [11]:
# Memory comparison
print("--- Memory Usage Comparison ---")
py_list = list(range(1000))
np_array = np.arange(1000)

--- Memory Usage Comparison ---


In [12]:
list_size = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list[:10]) * 100
array_size = np_array.nbytes

In [13]:
print(f"Python list (1000 items): ~{list_size/1024:.2f} KB")
print(f"NumPy array (1000 items): {array_size/1024:.2f} KB")
print(f"NumPy uses ~{list_size/array_size:.1f}x LESS memory!")

Python list (1000 items): ~35.21 KB
NumPy array (1000 items): 7.81 KB
NumPy uses ~4.5x LESS memory!


**Creating NumPy Arrays**

In [14]:
print("=" * 70)
print("Creating NumPy Arrays")
print("=" * 70)

Creating NumPy Arrays


In [15]:
# Method 1: From Python list
print("\n--- Creating Arrays from Lists ---")
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(f"Python list: {my_list}")
print(f"NumPy array: {arr}")
print(f"Type: {type(arr)}")


--- Creating Arrays from Lists ---
Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [16]:
# Create 2D array (matrix)
print("\n--- Creating 2D Arrays (Matrices) ---")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(matrix)
print(f"Shape: {matrix.shape}")
print(f"Dimensions: {matrix.ndim}")
print(f"Total elements: {matrix.size}")
print(f"Data type: {matrix.dtype}")


--- Creating 2D Arrays (Matrices) ---
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Total elements: 9
Data type: int64


In [17]:
# Method 2: Using arange()
print("\n--- Using np.arange() ---")
print(f"np.arange(10): {np.arange(10)}")
print(f"np.arange(5, 15): {np.arange(5, 15)}")
print(f"np.arange(0, 20, 2): {np.arange(0, 20, 2)}")
print(f"np.arange(10, 0, -1): {np.arange(10, 0, -1)}")


--- Using np.arange() ---
np.arange(10): [0 1 2 3 4 5 6 7 8 9]
np.arange(5, 15): [ 5  6  7  8  9 10 11 12 13 14]
np.arange(0, 20, 2): [ 0  2  4  6  8 10 12 14 16 18]
np.arange(10, 0, -1): [10  9  8  7  6  5  4  3  2  1]


In [18]:
# Method 3: Using linspace()
print("\n--- Using np.linspace() ---")
print(f"np.linspace(0, 10, 5): {np.linspace(0, 10, 5)}")
print(f"np.linspace(0, 1, 11): {np.linspace(0, 1, 11)}")


--- Using np.linspace() ---
np.linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
np.linspace(0, 1, 11): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [19]:
# Method 4: Arrays of zeros and ones
print("\n--- Arrays of Zeros and Ones ---")
print(f"Zeros (1D): {np.zeros(5)}")
print("Zeros (2D, 3x4):")
print(np.zeros((3, 4)))
print(f"\nOnes (1D): {np.ones(5)}")
print("Ones (2D, 2x3):")
print(np.ones((2, 3)))


--- Arrays of Zeros and Ones ---
Zeros (1D): [0. 0. 0. 0. 0.]
Zeros (2D, 3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (1D): [1. 1. 1. 1. 1.]
Ones (2D, 2x3):
[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Method 5: Identity matrix
print("\n--- Identity Matrix ---")
print("Identity Matrix (4x4):")
print(np.eye(4))


--- Identity Matrix ---
Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Method 6: Arrays filled with specific value
print("\n--- Arrays with Specific Values ---")
print(f"Array of 5s: {np.full(5, 5)}")
print("Matrix of 7s (3x3):")
print(np.full((3, 3), 7))


--- Arrays with Specific Values ---
Array of 5s: [5 5 5 5 5]
Matrix of 7s (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [22]:
# Method 7: Random arrays
print("\n--- Random Arrays ---")
print(f"Random floats (0-1): {np.random.rand(5)}")
print(f"Random integers (1-100): {np.random.randint(1, 100, 10)}")
print(f"Random normal distribution: {np.random.randn(5)}")


--- Random Arrays ---
Random floats (0-1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Random integers (1-100): [83 87 75 75 88 24  3 22 53  2]
Random normal distribution: [ 0.23309524  0.11799461  1.46237812  1.53871497 -2.43910582]


In [23]:
# Array attributes
print("\n--- Array Attributes ---")
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Array:")
print(arr)
print(f"Shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Data type: {arr.dtype}")
print(f"Item size: {arr.itemsize} bytes")
print(f"Total bytes: {arr.nbytes} bytes")


--- Array Attributes ---
Array:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Dimensions: 2
Size: 8
Data type: int64
Item size: 8 bytes
Total bytes: 64 bytes


**Array Indexing and Slicing**

In [24]:
print("=" * 70)
print("Array Indexing and Slicing")
print("=" * 70)

Array Indexing and Slicing


In [25]:
# 1D Array indexing
print("\n--- 1D Array Indexing ---")
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Array: {arr}")
print(f"First element [0]: {arr[0]}")
print(f"Third element [2]: {arr[2]}")
print(f"Last element [-1]: {arr[-1]}")
print(f"Second to last [-2]: {arr[-2]}")



--- 1D Array Indexing ---
Array: [ 10  20  30  40  50  60  70  80  90 100]
First element [0]: 10
Third element [2]: 30
Last element [-1]: 100
Second to last [-2]: 90


In [26]:
# 1D Array slicing
print("\n--- 1D Array Slicing ---")
print(f"Array: {arr}")
print(f"First 3 elements [:3]: {arr[:3]}")
print(f"Last 3 elements [-3:]: {arr[-3:]}")
print(f"Elements 2 to 5 [2:6]: {arr[2:6]}")
print(f"Every other element [::2]: {arr[::2]}")
print(f"Reverse array [::-1]: {arr[::-1]}")


--- 1D Array Slicing ---
Array: [ 10  20  30  40  50  60  70  80  90 100]
First 3 elements [:3]: [10 20 30]
Last 3 elements [-3:]: [ 80  90 100]
Elements 2 to 5 [2:6]: [30 40 50 60]
Every other element [::2]: [10 30 50 70 90]
Reverse array [::-1]: [100  90  80  70  60  50  40  30  20  10]


In [27]:
# 2D Array indexing and slicing
print("\n--- 2D Array Indexing ---")
matrix = np.array([[10, 20, 30, 40],
                   [50, 60, 70, 80],
                   [90, 100, 110, 120]])
print("Matrix:")
print(matrix)
print(f"\nElement at [0, 0]: {matrix[0, 0]}")
print(f"Element at [1, 2]: {matrix[1, 2]}")
print(f"Element at [2, 3]: {matrix[2, 3]}")


--- 2D Array Indexing ---
Matrix:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at [0, 0]: 10
Element at [1, 2]: 70
Element at [2, 3]: 120


In [28]:
print("\n--- 2D Array Slicing ---")
print("First row [0]:")
print(matrix[0])
print("\nFirst column [:, 0]:")
print(matrix[:, 0])
print("\nCenter 2x2 sub-matrix [1:3, 1:3]:")
print(matrix[1:3, 1:3])


--- 2D Array Slicing ---
First row [0]:
[10 20 30 40]

First column [:, 0]:
[10 50 90]

Center 2x2 sub-matrix [1:3, 1:3]:
[[ 60  70]
 [100 110]]


In [29]:
# Boolean indexing (filtering)
print("\n--- Boolean Indexing (Filtering) ---")
arr = np.array([10, 25, 30, 15, 40, 5, 35, 20])
print(f"Array: {arr}")
print(f"Values > 20: {arr[arr > 20]}")
print(f"Values <= 15: {arr[arr <= 15]}")
print(f"Values between 15 and 30: {arr[(arr >= 15) & (arr <= 30)]}")
print(f"Even numbers: {arr[arr % 2 == 0]}")


--- Boolean Indexing (Filtering) ---
Array: [10 25 30 15 40  5 35 20]
Values > 20: [25 30 40 35]
Values <= 15: [10 15  5]
Values between 15 and 30: [25 30 15 20]
Even numbers: [10 30 40 20]


In [30]:
# Copy vs View
print("\n--- Copy vs View (Important!) ---")
arr = np.array([1, 2, 3, 4, 5])
print(f"Original: {arr}")


--- Copy vs View (Important!) ---
Original: [1 2 3 4 5]


In [31]:
# View (shares memory)
view = arr[:]
view[0] = 999
print(f"After modifying view: {arr}  # Original changed!")

After modifying view: [999   2   3   4   5]  # Original changed!


In [32]:
# Copy (separate memory)
arr = np.array([1, 2, 3, 4, 5])
copy = arr.copy()
copy[0] = 999
print(f"After modifying copy: {arr}  # Original unchanged!")

After modifying copy: [1 2 3 4 5]  # Original unchanged!


**Array Operations (Element-wise)**

In [33]:
print("=" * 70)
print("Array Operations (Element-wise)")
print("=" * 70)

Array Operations (Element-wise)


In [34]:
# Basic arithmetic with arrays
print("\n--- Array Arithmetic (Element-wise) ---")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"\narr1 + arr2: {arr1 + arr2}")
print(f"arr1 - arr2: {arr1 - arr2}")
print(f"arr1 * arr2: {arr1 * arr2}")
print(f"arr1 / arr2: {arr1 / arr2}")
print(f"arr1 ** 2: {arr1 ** 2}")


--- Array Arithmetic (Element-wise) ---
arr1: [1 2 3 4 5]
arr2: [10 20 30 40 50]

arr1 + arr2: [11 22 33 44 55]
arr1 - arr2: [ -9 -18 -27 -36 -45]
arr1 * arr2: [ 10  40  90 160 250]
arr1 / arr2: [0.1 0.1 0.1 0.1 0.1]
arr1 ** 2: [ 1  4  9 16 25]


In [35]:
# Scalar operations (Broadcasting)
print("\n--- Scalar Operations (Broadcasting) ---")
arr = np.array([1, 2, 3, 4, 5])
print(f"arr: {arr}")
print(f"arr + 10: {arr + 10}")
print(f"arr * 3: {arr * 3}")
print(f"arr ** 2: {arr ** 2}")


--- Scalar Operations (Broadcasting) ---
arr: [1 2 3 4 5]
arr + 10: [11 12 13 14 15]
arr * 3: [ 3  6  9 12 15]
arr ** 2: [ 1  4  9 16 25]


In [36]:
# Comparison operations
print("\n--- Comparison Operations ---")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"arr1 == arr2: {arr1 == arr2}")
print(f"arr1 == arr2: {arr1 == arr2}")
print(f"arr1 > arr2: {arr1 > arr2}")
print(f"arr1 >= 3: {arr1 >= 3}")


--- Comparison Operations ---
arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
arr1 == arr2: [False False  True False False]
arr1 == arr2: [False False  True False False]
arr1 > arr2: [False False False  True  True]
arr1 >= 3: [False False  True  True  True]


In [37]:
# Mathematical functions
print("\n--- Mathematical Functions ---")
arr = np.array([1, 4, 9, 16, 25])
print(f"Array: {arr}")
print(f"Square root: {np.sqrt(arr)}")

arr2 = np.array([1, 2, 3, 4, 5])
print(f"\nArray: {arr2}")
print(f"Exponential (e^x): {np.exp(arr2)}")
print(f"Natural log (ln): {np.log(arr2)}")


--- Mathematical Functions ---
Array: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]

Array: [1 2 3 4 5]
Exponential (e^x): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log (ln): [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
# Trigonometric functions
print("\n--- Trigonometric Functions ---")
angles_deg = np.array([0, 30, 45, 60, 90])
angles_rad = np.deg2rad(angles_deg)

print(f"Angles (degrees): {angles_deg}")
print(f"Sin: {np.sin(angles_rad).round(3)}")
print(f"Cos: {np.cos(angles_rad).round(3)}")


--- Trigonometric Functions ---
Angles (degrees): [ 0 30 45 60 90]
Sin: [0.    0.5   0.707 0.866 1.   ]
Cos: [1.    0.866 0.707 0.5   0.   ]


In [39]:
# Quick aggregations
print("\n--- Quick Aggregations ---")
arr = np.array([10, 20, 30, 40, 50])
print(f"Array: {arr}")
print(f"Sum: {arr.sum()}")
print(f"Mean: {arr.mean()}")
print(f"Min: {arr.min()}")
print(f"Max: {arr.max()}")


--- Quick Aggregations ---
Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Min: 10
Max: 50


**Array Methods (Statistical Operations)**

In [40]:
print("=" * 70)
print("Array Methods (Statistical Operations)")
print("=" * 70)

Array Methods (Statistical Operations)


In [41]:
# Basic statistics
print("\n--- Basic Statistical Methods ---")
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
print(f"Array: {arr}")
print(f"\nSum: {arr.sum()}")
print(f"Mean (average): {arr.mean()}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {arr.std():.2f}")
print(f"Variance: {arr.var():.2f}")
print(f"Minimum: {arr.min()}")
print(f"Maximum: {arr.max()}")


--- Basic Statistical Methods ---
Array: [10 15 20 25 30 35 40 45 50]

Sum: 270
Mean (average): 30.0
Median: 30.0
Standard deviation: 12.91
Variance: 166.67
Minimum: 10
Maximum: 50


In [42]:
# Index of min/max
print("\n--- Finding Indices ---")
arr = np.array([64, 25, 12, 22, 11, 90])
print(f"Array: {arr}")
print(f"Index of minimum: {arr.argmin()}")
print(f"Index of maximum: {arr.argmax()}")
print(f"Minimum value at index {arr.argmin()}: {arr[arr.argmin()]}")
print(f"Maximum value at index {arr.argmax()}: {arr[arr.argmax()]}")


--- Finding Indices ---
Array: [64 25 12 22 11 90]
Index of minimum: 4
Index of maximum: 5
Minimum value at index 4: 11
Maximum value at index 5: 90


In [43]:
# Sorting
print("\n--- Sorting Arrays ---")
arr = np.array([12, 64, 25, 22, 10, 90])
print(f"Original: {arr}")
print(f"Sorted indices: {np.argsort(arr)}")
print(f"Sorted (ascending): {np.sort(arr)}")
print(f"Sorted (descending): {np.sort(arr)[::-1]}")


--- Sorting Arrays ---
Original: [12 64 25 22 10 90]
Sorted indices: [4 0 3 2 1 5]
Sorted (ascending): [10 12 22 25 64 90]
Sorted (descending): [90 64 25 22 12 10]


In [44]:
# Cumulative operations
print("\n--- Cumulative Operations ---")
arr = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr}")
print(f"Cumulative sum: {arr.cumsum()}")
print(f"Cumulative product: {arr.cumprod()}")


--- Cumulative Operations ---
Array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]


In [45]:
# Unique values and counts
print("\n--- Unique Values ---")
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])
print(f"Array: {arr}")
unique_vals, counts = np.unique(arr, return_counts=True)
print(f"Unique values: {unique_vals}")
print(counts)
print("Value counts:")
for val, count in zip(unique_vals, counts):
    print(f"  {val}: appears {count} times")


--- Unique Values ---
Array: [1 2 2 3 3 3 4 4 4 4 5]
Unique values: [1 2 3 4 5]
[1 2 3 4 1]
Value counts:
  1: appears 1 times
  2: appears 2 times
  3: appears 3 times
  4: appears 4 times
  5: appears 1 times


In [46]:
# Operations on 2D arrays
print("\n--- 2D Array Operations ---")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:")
print(matrix)
print(f"\nSum of all elements: {matrix.sum()}")
print(f"Mean of all elements: {matrix.mean():.2f}")


--- 2D Array Operations ---
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements: 45
Mean of all elements: 5.00


In [47]:
# Operations along axes
print("\n--- Operations Along Axes ---")
print("Axis 0 = columns (down), Axis 1 = rows (across)")
print(f"Sum of each column (axis=0): {matrix.sum(axis=0)}")
print(f"Sum of each row (axis=1): {matrix.sum(axis=1)}")


--- Operations Along Axes ---
Axis 0 = columns (down), Axis 1 = rows (across)
Sum of each column (axis=0): [12 15 18]
Sum of each row (axis=1): [ 6 15 24]


In [48]:
# Conditional operations
print("\n--- Conditional Operations ---")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Array: {arr}")
print(f"Count of values > 5: {(arr > 5).sum()}")
print(f"Percentage > 5: {(arr > 5).mean() * 100:.1f}%")


--- Conditional Operations ---
Array: [ 1  2  3  4  5  6  7  8  9 10]
Count of values > 5: 5
Percentage > 5: 50.0%


**Array Reshaping and Transposing**

In [49]:
print("=" * 70)
print("Array Reshaping and Transposing")
print("=" * 70)

Array Reshaping and Transposing


In [50]:
# Reshaping 1D to 2D
print("\n--- Reshaping 1D to 2D ---")
arr = np.arange(1, 13)
print(f"Original 1D array (12 elements): {arr}")
print(f"Shape: {arr.shape}")


--- Reshaping 1D to 2D ---
Original 1D array (12 elements): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)


In [51]:
reshaped_3x4 = arr.reshape(3, 4)
print("\nReshaped to 3x4 (3 rows, 4 columns):")
print(reshaped_3x4)
print(f"Shape: {reshaped_3x4.shape}")


Reshaped to 3x4 (3 rows, 4 columns):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [52]:
# Using -1 for automatic dimension calculation
print("\n--- Auto-dimension with -1 ---")
arr = np.arange(1, 13)
auto1 = arr.reshape(3, -1)  # 3 rows, auto-calculate columns
print(f"Reshape(3, -1) - 3 rows, auto columns:")
print(auto1)
print(f"Shape: {auto1.shape}")


--- Auto-dimension with -1 ---
Reshape(3, -1) - 3 rows, auto columns:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [53]:
# Flattening (2D to 1D)
print("\n--- Flattening Arrays ---")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 2D matrix:")
print(matrix)
print(f"\nFlattened: {matrix.flatten()}")


--- Flattening Arrays ---
Original 2D matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened: [1 2 3 4 5 6 7 8 9]


In [54]:
# Transpose
print("\n--- Transpose (Flip Rows and Columns) ---")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Original (2x3):")
print(matrix)
print(f"Shape: {matrix.shape}")


--- Transpose (Flip Rows and Columns) ---
Original (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [55]:
transposed = matrix.T
print("\nTransposed (3x2):")
print(transposed)
print(f"Shape: {transposed.shape}")


Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [56]:
# Adding dimensions
print("\n--- Adding Dimensions ---")
arr = np.array([1, 2, 3, 4, 5])
print(f"Original 1D: {arr}")
print(f"Shape: {arr.shape}")


--- Adding Dimensions ---
Original 1D: [1 2 3 4 5]
Shape: (5,)


In [57]:
# Add dimension at different axes
row_vector = arr.reshape(1, -1)
col_vector = arr.reshape(-1, 1)
print(f"\nRow vector (1x5) shape: {row_vector.shape}")
print(f"Column vector (5x1) shape: {col_vector.shape}")


Row vector (1x5) shape: (1, 5)
Column vector (5x1) shape: (5, 1)


In [58]:
# Stacking arrays
print("\n--- Stacking Arrays ---")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stack (stack rows)
vstacked = np.vstack([arr1, arr2])
print("Vertical stack:")
print(vstacked)

# Horizontal stack (stack columns)
hstacked = np.hstack([arr1, arr2])
print(f"\nHorizontal stack: {hstacked}")


--- Stacking Arrays ---
Vertical stack:
[[1 2 3]
 [4 5 6]]

Horizontal stack: [1 2 3 4 5 6]


**Broadcasting**

In [59]:
print("=" * 70)
print("Broadcasting in NumPy")
print("=" * 70)

print("\n--- What is Broadcasting? ---")
print("Broadcasting allows NumPy to work with arrays of different shapes")
print("during arithmetic operations.")

Broadcasting in NumPy

--- What is Broadcasting? ---
Broadcasting allows NumPy to work with arrays of different shapes
during arithmetic operations.


In [60]:
# Scalar broadcasting
print("\n--- Example 1: Scalar Broadcasting ---")
arr = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr}")
print(f"Array + 10: {arr + 10}")
print("→ Scalar 10 is broadcast to each element")


--- Example 1: Scalar Broadcasting ---
Array: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]
→ Scalar 10 is broadcast to each element


In [61]:
# 1D array with 2D array
print("\n--- 1D + 2D Broadcasting ---")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_vector = np.array([10, 20, 30])
col_vector = np.array([[10],
                           [20],
                           [30]])


--- 1D + 2D Broadcasting ---


In [62]:
print("Matrix:")
print(matrix)
print(f"\nRow vector: {row_vector}")
print(f"\nColumn vector: {col_vector}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row vector: [10 20 30]

Column vector: [[10]
 [20]
 [30]]


In [63]:
print("\nMatrix + Row vector:")
print(matrix + row_vector)
print("→ Row vector broadcast to each row of matrix")
print("\nMatrix + Column vector:")
print(matrix + col_vector)
print("→ Column vector broadcast to each column of matrix")


Matrix + Row vector:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
→ Row vector broadcast to each row of matrix

Matrix + Column vector:
[[11 12 13]
 [24 25 26]
 [37 38 39]]
→ Column vector broadcast to each column of matrix


In [64]:
# Broadcasting rules visualization
print("\n--- Broadcasting Rules ---")
print("Rule 1: Arrays have same shape → Works")
a1 = np.ones((3, 4))
a2 = np.ones((3, 4))
print(f"Shape {a1.shape} + Shape {a2.shape} = Works")

print("\nRule 2: One array has dimension 1 → Works")
a3 = np.ones((3, 1, 4))
a4 = np.ones((1, 5, 1))
print(f"Shape {a3.shape} * Shape {a4.shape} = Works")
print(a3)
print(a4)


--- Broadcasting Rules ---
Rule 1: Arrays have same shape → Works
Shape (3, 4) + Shape (3, 4) = Works

Rule 2: One array has dimension 1 → Works
Shape (3, 1, 4) * Shape (1, 5, 1) = Works
[[[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]]
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [65]:
# Practical broadcasting applications
print("\n--- Practical Broadcasting Applications ---")


--- Practical Broadcasting Applications ---


In [66]:
# 1. Normalizing data (feature scaling)
data = np.random.randn(100, 3) * 10 + 5  # 100 samples, 3 features
mean = data.mean(axis=0)  # Shape: (3,)
std = data.std(axis=0)    # Shape: (3,)
normalized = (data - mean) / std  # Broadcasting happens here!

In [67]:
print("1. Data Normalization:")
print(f"   Data shape: {data.shape}")
print(f"   Mean shape: {mean.shape}")
print(f"   Normalized mean: {normalized.mean(axis=0).round(3)}")
print(f"   Normalized std: {normalized.std(axis=0).round(3)}")

1. Data Normalization:
   Data shape: (100, 3)
   Mean shape: (3,)
   Normalized mean: [-0.  0. -0.]
   Normalized std: [1. 1. 1.]


In [68]:
# 2. Outer product (without loops)
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6, 7])
outer_product = vector1[:, np.newaxis] * vector2

In [69]:
print("\n2. Outer Product:")
print(f"   Vector 1: {vector1}")
print(f"   Vector 2: {vector2}")
print(f"   Outer product (3x4):")
print(outer_product)


2. Outer Product:
   Vector 1: [1 2 3]
   Vector 2: [4 5 6 7]
   Outer product (3x4):
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]


**Advanced Concepts: Data Types and Memory**

In [70]:
print("=" * 70)
print("ADVANCED: Understanding Data Types and Memory")
print("=" * 70)

# Understanding Data Types in NumPy
print("\nUnderstanding Data Types in NumPy:")
print("-" * 40)

ADVANCED: Understanding Data Types and Memory

Understanding Data Types in NumPy:
----------------------------------------


In [71]:
# Explicit dtype specification
int8_array = np.array([1, 2, 3], dtype=np.int8)
int32_array = np.array([1, 2, 3], dtype=np.int32)
float64_array = np.array([1, 2, 3], dtype=np.float64)

In [72]:
print(f"int8 array: {int8_array} | Memory: {int8_array.nbytes} bytes")
print(f"int32 array: {int32_array} | Memory: {int32_array.nbytes} bytes")
print(f"float64 array: {float64_array} | Memory: {float64_array.nbytes} bytes")

int8 array: [1 2 3] | Memory: 3 bytes
int32 array: [1 2 3] | Memory: 12 bytes
float64 array: [1. 2. 3.] | Memory: 24 bytes


In [73]:
# Memory-efficient arrays
print("\nMemory Efficiency Example:")
print("-" * 40)
size = 10_000_000


Memory Efficiency Example:
----------------------------------------


In [75]:
# NumPy with different dtypes
np_int8 = np.arange(size, dtype=np.int8)
np_int64 = np.arange(size, dtype=np.int64)

print(f"NumPy int8 array: {np_int8.nbytes/1e6:.1f} MB")
print(f"NumPy int64 array: {np_int64.nbytes/1e6:.1f} MB")
print(f"Memory saving: {np_int64.nbytes/np_int8.nbytes:.0f}x with int8!")

NumPy int8 array: 10.0 MB
NumPy int64 array: 80.0 MB
Memory saving: 8x with int8!


In [76]:
# Fancy indexing
print("\nFancy Indexing Examples:")
print("-" * 40)


Fancy Indexing Examples:
----------------------------------------


In [85]:
arr = np.arange(100).reshape(10, 10)

In [87]:
# Select specific rows and columns
rows = [1, 3, 5]
cols = [2, 4, 6]
selected = arr[rows][:, cols]
print(f"Rows {rows}, Columns {cols}:")
print(selected)

Rows [1, 3, 5], Columns [2, 4, 6]:
[[12 14 16]
 [32 34 36]
 [52 54 56]]


In [93]:
# Boolean indexing with multiple conditions
data = np.random.randint(0, 100, 50)
mask = (data > 20) & (data < 80) & (data % 3 == 0)
print(f"\nValues between 20-80 divisible by 3: {data[mask]}")


Values between 20-80 divisible by 3: [78 63 78 51 78]


**Universal Functions (UFuncs)**

In [95]:
print("=" * 70)
print("UNIVERSAL FUNCTIONS (UFUNCS)")
print("=" * 70)

UNIVERSAL FUNCTIONS (UFUNCS)


In [ ]:
# Creating custom ufuncs
def custom_function(x, y):
    """Custom mathematical operation"""
    return x**2 + np.sin(y)

In [97]:
# Vectorize the function
vectorized_func = np.vectorize(custom_function, otypes=[float])
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
result = vectorized_func(arr1, arr2)
print(f"Custom ufunc result: {result}")

Custom ufunc result: [ 1.  5.  9. 15.]
